[tool.poetry]
name = "mothertongues"
version = "0.1.0"
description = ""
authors = ["roedoejet <hello@aidanpine.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.88.0"
loguru = "^0.6.0"
typer = "^0.7.0"
pandas = "^1.5.2"
httpx = "^0.23.1"
gitlint = "^0.19.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.10.1"
black = "^22.12.0"
mypy = "^0.991"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
